# **ضرب بردار در ماتریس**

برای انجام این کار در پایتون، شما می‌توانید از کتابخانه $NumPy$ استفاده کنید که یک کتابخانه قدرتمند برای انجام محاسبات عددی در پایتون می‌باشد. ابتدا کتابخانه $NumPy$ را وارد کنید و سپس بردار و ماتریس را از ورودی کاربر دریافت نمایید و ضرب آن‌ها را محاسبه کنید. در زیر یک نمونه کد برای این کار آورده‌شده است:

توجه داشته باشید که ابعاد بردار و سطر‌های ماتریس باید با هم برابر باشند تا بتوان ضرب داخلی $(dot product)$ را انجام داد.



لطفا طول بردار را وارد کنید: 3
لطفا تعداد سطرهای ماتریس را وارد کنید: 3
لطفا تعداد ستون‌های ماتریس را وارد کنید: 3
مقدار 1 بردار را وارد کنید: 1
مقدار 2 بردار را وارد کنید: 2
مقدار 3 بردار را وارد کنید: 3
مقدار (1, 1) ماتریس را وارد کنید: 1
مقدار (1, 2) ماتریس را وارد کنید: 2
مقدار (1, 3) ماتریس را وارد کنید: 3
مقدار (2, 1) ماتریس را وارد کنید: 4
مقدار (2, 2) ماتریس را وارد کنید: 5
مقدار (2, 3) ماتریس را وارد کنید: 6
مقدار (3, 1) ماتریس را وارد کنید: 7
مقدار (3, 2) ماتریس را وارد کنید: 8
مقدار (3, 3) ماتریس را وارد کنید: 9
نتیجه ضرب بردار در ماتریس: [30. 36. 42.]


# **ضرب ماتریس در بردار**


ضرب یک ماتریس در یک بردار معمولاً به عنوان ضرب ماتریس در یک بردار ستونی در نظر گرفته می‌شود، که در آن بردار از سمت راست ماتریس ضرب می‌شود. به یاد داشته باشید که تعداد ستون‌های ماتریس باید برابر با تعداد عناصر بردار باشد. در اینجا یک نمونه کد پایتون برای دریافت یک ماتریس و یک بردار از کاربر و محاسبه ضرب ماتریس در بردار استفاده می‌کنیم

این کد ابتدا سایز ماتریس و بردار را مشخص می‌کند و سپس از کاربر می‌خواهد که مقادیر لازم را وارد کند تا ضرب انجام شود. توجه داشته باشید که باید تعداد سطرها، ستون‌ها، و ابعاد بردار درست وارد شوند تا ضرب ماتریسی ممکن باشد

In [2]:
import numpy as np

# دریافت ابعاد ماتریس و بردار از کاربر
matrix_rows = int(input('لطفا تعداد سطرهای ماتریس را وارد کنید: '))
matrix_columns = int(input('لطفا تعداد ستون‌های ماتریس را وارد کنید: '))  # این باید برابر با طول بردار باشد

# بررسی امکان ضرب ماتریس در بردار
vector_length = int(input('لطفا طول بردار را وارد کنید: '))
if matrix_columns != vector_length:
    print(f"ضرب ماتریس در بردار ممکن نیست زیرا تعداد ستون‌های ماتریس با طول بردار برابر نیست.")
else:
    # دریافت عناصر ماتریس از کاربر
    matrix = []
    for i in range(matrix_rows):
        row = []
        for j in range(matrix_columns):
            value = float(input(f'مقدار ({i+1}, {j+1}) ماتریس را وارد کنید: '))
            row.append(value)
        matrix.append(row)

    # دریافت مولفه‌های بردار از کاربر
    vector = []
    for i in range(vector_length):
        value = float(input(f'مقدار {i+1} بردار را وارد کنید: '))
        vector.append(value)

    # تبدیل لیست‌ها به آرایه‌های Numpy
    matrix_np = np.array(matrix)
    vector_np = np.array(vector)

    # محاسبه ضرب ماتریس در بردار
    result = np.dot(matrix_np, vector_np)

    # نمایش نتیجه
    print("نتیجه ضرب ماتریس در بردار:")
    print(result)

لطفا تعداد سطرهای ماتریس را وارد کنید: 3
لطفا تعداد ستون‌های ماتریس را وارد کنید: 3
لطفا طول بردار را وارد کنید: 3
مقدار (1, 1) ماتریس را وارد کنید: 1
مقدار (1, 2) ماتریس را وارد کنید: 2
مقدار (1, 3) ماتریس را وارد کنید: 3
مقدار (2, 1) ماتریس را وارد کنید: 4
مقدار (2, 2) ماتریس را وارد کنید: 5
مقدار (2, 3) ماتریس را وارد کنید: 6
مقدار (3, 1) ماتریس را وارد کنید: 7
مقدار (3, 2) ماتریس را وارد کنید: 8
مقدار (3, 3) ماتریس را وارد کنید: 9
مقدار 1 بردار را وارد کنید: 1
مقدار 2 بردار را وارد کنید: 2
مقدار 3 بردار را وارد کنید: 3
نتیجه ضرب ماتریس در بردار:
[14. 32. 50.]


# **ضرب ماتریس در ماتریس**


برای ضرب ماتریس در ماتریس دیگری در پایتون، از کتابخانه $NumPy$ استفاده می‌کنیم. همانطور که قبلا گفتیم، برای ضرب دو ماتریس در هم، تعداد ستون‌های ماتریس اول باید برابر با تعداد سطرهای ماتریس دوم باشد.

در زیر یک نمونه کد برای انجام این کار آورده شده است:

لازم به ذکر است، هنگامی که از کاربر ورودی می‌گیرید، مهم است که داده‌ها را به درستی وارد کنید تا از خطای ابعاد جلوگیری شود. $NumPy$ به صورت خودکار سایز ماتریس‌ها را چک می‌کند و اگر غیرقابل ضرب باشند خطا برمی‌گرداند

In [3]:
import numpy as np

# دریافت ابعاد ماتریس اول از کاربر
rows_a = int(input('لطفا تعداد سطرهای ماتریس اول را وارد کنید: '))
columns_a = int(input('لطفا تعداد ستون‌های ماتریس اول را وارد کنید: '))

# دریافت عناصر ماتریس اول از کاربر
matrix_a = []
for i in range(rows_a):
    row = []
    for j in range(columns_a):
        value = float(input(f'مقدار ({i + 1}, {j + 1}) ماتریس اول را وارد کنید: '))
        row.append(value)
    matrix_a.append(row)

# دریافت ابعاد ماتریس دوم از کاربر
rows_b = int(input('لطفا تعداد سطرهای ماتریس دوم را وارد کنید: '))
columns_b = int(input('لطفا تعداد ستون‌های ماتریس دوم را وارد کنید: '))

# اطمینان از اینکه ضرب ماتریس ممکن است
if columns_a != rows_b:
    print('ضرب این دو ماتریس ممکن نیست. تعداد ستون‌های ماتریس اول باید برابر با تعداد سطرهای ماتریس دوم باشد.')
else:
    # دریافت عناصر ماتریس دوم از کاربر
    matrix_b = []
    for i in range(rows_b):
        row = []
        for j in range(columns_b):
            value = float(input(f'مقدار ({i + 1}, {j + 1}) ماتریس دوم را وارد کنید: '))
            row.append(value)
        matrix_b.append(row)

    # تبدیل لیست‌ها به آرایه‌های NumPy
    matrix_a_np = np.array(matrix_a)
    matrix_b_np = np.array(matrix_b)

    # محاسبه ضرب دو ماتریس
    result = np.dot(matrix_a_np, matrix_b_np)

    # نمایش نتیجه
    print('نتیجه ضرب دو ماتریس:')
    print(result)

لطفا تعداد سطرهای ماتریس اول را وارد کنید: 3
لطفا تعداد ستون‌های ماتریس اول را وارد کنید: 3
مقدار (1, 1) ماتریس اول را وارد کنید: 1
مقدار (1, 2) ماتریس اول را وارد کنید: 2
مقدار (1, 3) ماتریس اول را وارد کنید: 3
مقدار (2, 1) ماتریس اول را وارد کنید: 4
مقدار (2, 2) ماتریس اول را وارد کنید: 5
مقدار (2, 3) ماتریس اول را وارد کنید: 6
مقدار (3, 1) ماتریس اول را وارد کنید: 7
مقدار (3, 2) ماتریس اول را وارد کنید: 8
مقدار (3, 3) ماتریس اول را وارد کنید: 9
لطفا تعداد سطرهای ماتریس دوم را وارد کنید: 3
لطفا تعداد ستون‌های ماتریس دوم را وارد کنید: 3
مقدار (1, 1) ماتریس دوم را وارد کنید: 1
مقدار (1, 2) ماتریس دوم را وارد کنید: 2
مقدار (1, 3) ماتریس دوم را وارد کنید: 3
مقدار (2, 1) ماتریس دوم را وارد کنید: 4
مقدار (2, 2) ماتریس دوم را وارد کنید: 5
مقدار (2, 3) ماتریس دوم را وارد کنید: 6
مقدار (3, 1) ماتریس دوم را وارد کنید: 7
مقدار (3, 2) ماتریس دوم را وارد کنید: 8
مقدار (3, 3) ماتریس دوم را وارد کنید: 9
نتیجه ضرب دو ماتریس:
[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]


# **$LU$**
در پایتون می‌توانید از کتابخانه $numpy$ برای ساخت ماتریس و انجام تجزیه $LU$ استفاده کنید. مثال زیر نحوه انجام این کار را نشان می‌دهد:

در این مثال، ابتدا اندازه ماتریس از کاربر گرفته می‌شود، سپس اعضای ماتریس وارد برنامه شده و در نهایت تجزیه $LU$ انجام می‌شود.



In [5]:
import numpy as np
import scipy.linalg
# دریافت اندازه ماتریس از کاربر
n = int(input("Enter the size of the square matrix: "))

# ساخت یک ماتریس خالی
A = np.zeros((n, n))

# دریافت اعضای ماتریس از کاربر
print("Enter the elements of the matrix:")
for i in range(n):
    for j in range(n):
        A[i][j] = float(input(f"A[{i}][{j}]: "))

# انجام تجزیه LU
P, L, U = scipy.linalg.lu(A)

print("P:")
print(P)
print("L:")
print(L)
print("U:")
print(U)
result = np.dot(P,np.dot(L, U))
print("result")
print(result)

Enter the size of the square matrix: 3
Enter the elements of the matrix:
A[0][0]: 1
A[0][1]: 2
A[0][2]: 3
A[1][0]: 4
A[1][1]: 5
A[1][2]: 6
A[2][0]: 7
A[2][1]: 8
A[2][2]: 9
P:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L:
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
U:
[[7.         8.         9.        ]
 [0.         0.85714286 1.71428571]
 [0.         0.         0.        ]]
result
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# **تجزیه چولسکی**

توجه داشته باشید که این کد فرض می‌کند ماتریس $( A^TA )$ مثبت معین است و قابل تجزیه چولسکی است، که تنها در این صورت تجزیه چولسکی امکان‌پذیر می‌باشد. همچنین، این کد فقط برای ماتریس‌های سه سه ساخته شده است، بنابراین برای آرایه‌های با اندازه‌های دیگر باید تعمیم یابد.

In [1]:
import numpy as np
import math

# دریافت تعداد سطرها و ستون‌ها از کاربر
R = int(input("تعداد سطرها را وارد کنید:"))
C = int(input("تعداد ستون‌ها را وارد کنید:"))

# دریافت ورودی‌های ماتریس A از کاربر
A = []
print("عناصر ماتریس را به صورت ردیفی وارد کنید:")
for i in range(R):
    a = []
    for j in range(C):
        a.append(int(input()))
    A.append(a)

# دریافت ورودی‌های ماتریس B از کاربر (در اینجا فقط یک ستون وجود دارد)
C = 1
B = []
print("عناصر ماتریس را به صورت ردیفی وارد کنید:")
for i in range(R):
    a = []
    for j in range(C):
        a.append(int(input()))
    B.append(a)

# تبدیل لیست به آرایه‌های نامپای (NumPy Array)
A = np.array(A)
B = np.array(B)

# نمایش ماتریس‌های A و B
print("A: \n", A)
print("B: \n", B)

# محاسبه ماتریس ترانهاده A و نمایش آن
At = A.transpose()
print("A Transpose: \n", At)

# محاسبه ضرب ماتریس ترانهاده در ماتریس A و نمایش آن
AtA = At.dot(A)
print("A Transpose * A: \n", AtA)

# محاسبه ضرب ماتریس ترانهاده در ماتریس B و نمایش آن
C = At.dot(B)
print("C: \n", C)

# اعمال تجزیه چولسکی برای ماتریس AtA
# محاسبه ماتریس H که مثلثی بالایی است
h11 = math.sqrt(AtA[0][0])
h21 = AtA[1][0] / h11
h31 = AtA[2][0] / h11
h22 = math.sqrt(AtA[1][1] - h21**2)
h32 = (AtA[2][1] - (h31 * h21)) / h22
h33 = math.sqrt(AtA[2][2] - (h31**2) - (h32**2))
H = np.array([[h11, 0, 0], [h21, h22, 0], [h31, h32, h33]])

# نمایش ماتریس H
print("H: \n", H)

# حل معادله خطی به روش جایگزینی رو به جلو (Forward substitution)
# برای محاسبه ماتریس Y
y1 = C[0][0] / h11
y2 = (C[1][0] - (h21 * y1)) / h22
y3 = (C[2][0] - (h31 * y1) - (h32 * y2)) / h33
Y = np.array([[y1, y2, y3]])

# نمایش ماتریس Y
print("Y: \n", Y)

# حل معادله خطی به روش جایگزینی رو به عقب (Backward substitution)
# برای محاسبه ماتریس X (پاسخ)
x3 = y3 / h33
x2 = (y2 - (h32 * x3)) / h22
x1 = (y1 - (h31 * x3) - (h21 * x2)) / h11
X = np.array([[x1, x2, x3]])

# نمایش ماتریس X (پاسخ نهایی معادله)
print("X: \n", X)

Enter the number of rows:4
Enter the number of columns:3
Enter the entries rowwise:
1
2
1
2
3
4
1
-1
2
1
-2
3
Enter the entries rowwise:
2
1
3
4
A : 
 [[ 1  2  1]
 [ 2  3  4]
 [ 1 -1  2]
 [ 1 -2  3]]
B : 
 [[2]
 [1]
 [3]
 [4]]
A.transpose : 
 [[ 1  2  1  1]
 [ 2  3 -1 -2]
 [ 1  4  2  3]]
A.transpose * A : 
 [[ 7  5 14]
 [ 5 18  6]
 [14  6 30]]
C : 
 [[11]
 [-4]
 [24]]
H  : 
 [[ 2.64575131  0.          0.        ]
 [ 1.88982237  3.79849594  0.        ]
 [ 5.29150262 -1.05304838  0.94397516]]
Y  : 
 [[ 4.1576092  -3.12153627 -1.36351968]]
X  : 
 [[ 5.33333333 -1.22222222 -1.44444444]]


# **نرم**


برای اینکه ابعاد و عناصر یک ماتریس را از کاربر دریافت کرده و سپس نرم یک $(L1 norm)$، نرم دو $(L2 norm)$ و نرم فروبنیوس $(Frobenius norm)$ آن را محاسبه کنیم، می‌توانیم از کتابخانه NumPy در پایتون استفاده کنیم. در ادامه، یک نمونه کد برای این منظور آمده است:

در این کد، ابتدا تعداد سطرها و ستون‌ها از کاربر گرفته می‌شود و سپس یک حلقه برای دریافت مقادیر ماتریس از کاربر وجود دارد. پس از تعریف ماتریس، سه نوع نرم مختلف با استفاده از تابع $np.linalg.norm$ محاسبه می‌شوند.

لطفاً توجه کنید که:

نرم یک بیشترین مجموع مقادیر مطلق ستون‌ها را نشان می‌دهد.

نرم دو (که گاهی به عنوان نرم اسپکترال هم شناخته می‌شود) با استفاده از بزرگ‌ترین مقدار ویژه ماتریس محاسبه می‌شود که برای ماتریس های مربعی منطبق است.

نرم فروبنیوس برابر با ریشه دوم مجموع مربعات همه عناصر ماتریس است که بیانگر فاصله مقادیر ماتریس از صفر است.

In [9]:
import numpy as np

# دریافت ابعاد ماتریس از کاربر
rows = int(input('لطفا تعداد سطرهای ماتریس را وارد کنید: '))
columns = int(input('لطفا تعداد ستون‌های ماتریس را وارد کنید: '))

# دریافت عناصر ماتریس از کاربر
matrix = []
for i in range(rows):
    row = []
    for j in range(columns):
        value = float(input(f'مقدار ({i + 1}, {j + 1}) ماتریس را وارد کنید: '))
        row.append(value)
    matrix.append(row)

# تبدیل لیست به آرایه NumPy
matrix_np = np.array(matrix)

# محاسبه نرم‌ها
norm_1 = np.linalg.norm(A, 1)        # ماکزیمم مجموع مطلق ستون‌ها
norm_2 = np.linalg.norm(A, 2)        # بزرگترین مقدار ویژه (نرم اسپکترال)
frobenius_norm = np.linalg.norm(A)   # ریشه دوم مجموع مربعات همه عناصر

# نمایش نتایج
print(f"نرم یک (L1 Norm): {norm_1}")
print(f"نرم دو (L2 Norm): {norm_2}")
print(f"نرم فروبنیوس (Frobenius Norm): {frobenius_norm}")

لطفا تعداد سطرهای ماتریس را وارد کنید: 3
لطفا تعداد ستون‌های ماتریس را وارد کنید: 3
مقدار (1, 1) ماتریس را وارد کنید: 1
مقدار (1, 2) ماتریس را وارد کنید: 2
مقدار (1, 3) ماتریس را وارد کنید: 3
مقدار (2, 1) ماتریس را وارد کنید: 4
مقدار (2, 2) ماتریس را وارد کنید: 5
مقدار (2, 3) ماتریس را وارد کنید: 6
مقدار (3, 1) ماتریس را وارد کنید: 7
مقدار (3, 2) ماتریس را وارد کنید: 8
مقدار (3, 3) ماتریس را وارد کنید: 9
نرم یک (L1 Norm): 6.0
نرم دو (L2 Norm): 3.7416573867739413
نرم فروبنیوس (Frobenius Norm): 3.7416573867739413


# **$( L_p )$**


در این کد، کاربر ابتدا تعداد سطرها و ستون‌های ماتریس و سپس مقادیر درون آن را وارد می‌کند. بعد از آن، مقدار $( p )$ از کاربر گرفته شده و نرم $( L_p )$ ماتریس با استفاده از تابع $matrix*Lp*norm$ محاسبه و نمایش داده می‌شود.

In [14]:
import numpy as np

# دریافت ابعاد ماتریس از کاربر
rows = int(input('لطفا تعداد سطرهای ماتریس را وارد کنید: '))
columns = int(input('لطفا تعداد ستون‌های ماتریس را وارد کنید: '))

# دریافت عناصر ماتریس از کاربر
matrix = []
for i in range(rows):
    row = []
    for j in range(columns):
        value = float(input(f'مقدار ({i + 1}, {j + 1}) ماتریس را وارد کنید: '))
        row.append(value)
    matrix.append(row)

def matrix_lp_norm(A, p=2):
    # محاسبه نرم L^p برای ماتریس A با استفاده از پارامتر p
    return np.power(np.sum(np.power(np.abs(A), p)), 1/p)

# تبدیل لیست به آرایه NumPy
matrix_np = np.array(matrix)

# دریافت مقدار p از کاربر
p = float(input("مقدار p را وارد کنید: "))

# محاسبه و نمایش نرم L^p
lp_norm = matrix_lp_norm(A, p)
print(f"L_p نرم ماتریس: {lp_norm}")

لطفا تعداد سطرهای ماتریس را وارد کنید: 3
لطفا تعداد ستون‌های ماتریس را وارد کنید: 3
مقدار (1, 1) ماتریس را وارد کنید: 1
مقدار (1, 2) ماتریس را وارد کنید: 2
مقدار (1, 3) ماتریس را وارد کنید: 3
مقدار (2, 1) ماتریس را وارد کنید: 4
مقدار (2, 2) ماتریس را وارد کنید: 5
مقدار (2, 3) ماتریس را وارد کنید: 6
مقدار (3, 1) ماتریس را وارد کنید: 7
مقدار (3, 2) ماتریس را وارد کنید: 8
مقدار (3, 3) ماتریس را وارد کنید: 9
مقدار p را وارد کنید: 2.65
L_p نرم ماتریس: 3.4023633455082924


# **حل دستگاه معادلات کمترین مربعات**


برای حل دستگاه معادلات کمترین مربعات با استفاده از معادلات نرمال، شما می‌توانید از $NumPy$ و تابع $np.linalg.lstsq$ استفاده کنید، که مستقیماً دستگاه کمترین مربعات را حل می‌کند. این کار عموماً با استفاده از معادله $( A^TAx = A^Tb )$ صورت می‌گیرد، جایی که $( A )$ ماتریس طراحی، $( b )$ وکتور پاسخ‌ها و $( x )$ وکتور نامعلوم‌ها است.

در زیر یک نمونه کد نشان داده شده است که نشان می‌دهد چگونه یک دستگاه کمترین مربعات را با استفاده از $NumPy$ حل کنید

تابع $np.linalg.solve$ برای حل معادله ماتریسی $( A^TAx = A^Tb )$ به کار می‌رود و مقادیر بهینه $( x )$ را بازمی‌گرداند. این روش مستقیماً معادلات نرمال را حل می‌کند و به شما وکتور $( x )$ را می‌دهد که دستگاه کمترین مربعات را حل می‌کند.

توجه داشته باشید که $np.linalg.lstsq$ پیش‌فرضی روش‌های پایدارتر و موثرتری را برای حل دستگاه کمترین مربعات انجام می‌دهد و نیازی به کار کردن مستقیم با معادلات نرمال نیست

In [4]:
import numpy as np

# فرض کنید A ماتریس طراحی و b وکتور پاسخ‌ها است
# مقادیر واقعی A و b باید مطابق با داده‌های مسئله تعریف شوند
A = np.array([[2, 1], [1, 1], [2, 2]])
b = np.array([5, 3, 6])

# استفاده از تابع lstsq برای حل دستگاه کمترین مربعات
# متغیر rcond=-1 به numpy دستور می‌دهد تا از کوچکترین مقدار مفید استفاده کند
x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)

# نمایش نتیجه
print('حل دستگاه کمترین مربعات:', x)

# اگر می‌خواهید معادلات نرمال (Normal Equations) را به‌طور دقیق حل کنید:
# ATA = A^TA
# ATb = A^Tb
ATA = A.T.dot(A)
ATb = A.T.dot(b)

# حل معادله نرمال: ATA * x = ATb
x_normal = np.linalg.solve(ATA, ATb)

# نمایش حل معادله نرمال
print('حل معادلات نرمال:', x_normal)

حل دستگاه کمترین مربعات: [2. 1.]
حل معادلات نرمال: [2. 1.]


# **$QR$**


تجزیه $QR$ یک ماتریس به محاسبه دو ماتریس $Q$ و $R$ می‌پردازد به‌طوری که ماتریس $Q$ یک ماتریس متعامد (در صورت ماتریس‌های حقیقی) یا یک ماتریس یونیتار (در صورت ماتریس‌های مختلط) و ماتریس $R$ یک ماتریس مثلثی بالایی است. تجزیه $QR$ می‌تواند برای حل دستگاه‌های معادلات خطی استفاده شود.

در پایتون، می‌توانید از کتابخانه $NumPy$ و تابع $np.linalg.qr$ برای انجام تجزیه $QR$ استفاده کنید:

در این کد، مراحل زیر را دنبال می‌کنیم:

تعریف ماتریس $A$ که می‌خواهیم تجزیه $QR$ روی آن انجام دهیم.


استفاده از تابع

$np.linalg.qr$

 برای به‌دست آوردن ماتریس‌های

 $Q$ و $R$.

اختیاری: در صورتی که بخواهید از تجزیه $QR$ برای حل یک دستگاه معادلات خطی استفاده کنید، می‌توانید $( Q^Tb )$ را محاسبه کنید و سپس معادله $( Rx = Q^Tb )$ را حل کنید تا پاسخ $( x )$ را پیدا کنید.

In [5]:
import numpy as np

# فرض کنید A یک ماتریس مستطیلی است که ابعاد آن در دستگاه معادلات خطی استفاده شده
# مقادیر واقعی A باید مطابق با داده‌های مسئله تعریف شوند
A = np.array([[2, 1], [1, 1], [2, 2]])

# انجام تجزیه QR
Q, R = np.linalg.qr(A)

# نمایش نتایج
print('ماتریس Q (متعامد/یونیتار):')
print(Q)
print('\nماتریس R (مثلثی بالایی):')
print(R)

# اگر قصد حل دستگاه معادلات Ax = b را داریم، می‌توانیم از تجزیه QR برای محاسبه x استفاده کنیم
b = np.array([5, 3, 6])

# محاسبه Q^Tb (معادله‌ی جایگزین)
Q_T_b = Q.T.dot(b)

# حل معادله R * x = Q^Tb برای بدست آوردن مقادیر x
# توجه: np.linalg.solve فقط معادلاتی با ماتریس‌های مربعی را حل می‌کند
# در اینجا، اگر A مستطیلی باشد، R و Q_T_b باید متناسب با ابعاد نهایی تنظیم شوند
x = np.linalg.solve(R, Q_T_b)

# نمایش حل x
print('\nحل دستگاه معادلات با تجزیه QR:')
print(x)

ماتریس Q (متعامد/یونیتار):
[[-0.66666667  0.74535599]
 [-0.33333333 -0.2981424 ]
 [-0.66666667 -0.59628479]]

ماتریس R (مثلثی بالایی):
[[-3.         -2.33333333]
 [ 0.         -0.74535599]]

حل دستگاه معادلات با تجزیه QR:
[2. 1.]


# **تبدیل هاوس‌هولدر**


تبدیل هاوس‌هولدر یکی از ابزارهای مورد استفاده در تجزیه‌های ماتریسی مثل تجزیه $QR$ است. ایده‌ی اصلی این تبدیل ایجاد یک ماتریس بازتاب $(Reflection matrix)$ به نام $( P )$ است که زمانی که با یک بردار $( x )$ ضرب شود، نتیجه یک بردار در جهت یکی از محورهای مختصات با اندازه‌ی $(x )$ خواهد بود.

یکی از استفاده‌های تبدیل هاوس‌هولدر، صفر کردن عناصر زیر قطر اصلی ماتریس در تجزیه $QR$ است. به منظور ایجاد یک ماتریس بازتاب هاوس‌هولدر برای بردار $( x )$، ابتدا یک بردار واحد $( e )$ را انتخاب می‌کنیم که تنها در جزء اول آن ۱ و در بقیه ۰ باشد، سپس بردار $( u )$ را بدین صورت محاسبه می‌کنیم: $( u = x -xe )$. ماتریس بازتاب هاوس‌هولدر $( P )$ نیز به صورت $( P = I - 2\frac{uu^T}{u^Tu} )$ است، که در آن $( I )$ ماتریس همانی است. اکنون ضرب $( Px )$ یک بردار در جهت $( e )$ به اندازه $(x )$ خواهد بود.

در زیر یک برنامه ساده پایتون برای ایجاد یک ماتریس بازتاب هاوس‌هولدر برای یک بردار $( x )$ داده شده است:

این کد یک تابع برای ایجاد ماتریس بازتاب هاوس‌هولدر تعریف می‌کند و آن را به یک بردار اعمال می‌کند تا نتیجه را به ما نشان دهد. توجه داشته باشید که این کد تنها برای یک بردار انجام می‌شود و در فرآیند واقعی تجزیه‌ی $QR$، معمولاً این تبدیلات را به تک‌تک ستون‌های ماتریس اعمال می‌کنند تا ماتریس $R$ مثلثی بالایی بدست آید.

In [6]:
import numpy as np

def householder_transformation(x):
    """
    ایجاد ماتریس بازتاب هاوس‌هولدر برای بردار x.
    """
    n = x.shape[0]
    e = np.zeros_like(x)
    e[0] = 1
    u = x + np.copysign(np.linalg.norm(x), x[0]) * e
    v = u / np.linalg.norm(u)
    H = np.eye(n) - 2 * np.outer(v, v)
    return H

# فرض کنید x یک بردار است
x = np.array([4, 1, 3, 2], dtype=float)

# محاسبه ماتریس بازتاب هاوس‌هولدر
H = householder_transformation(x)

# نمایش ماتریس H
print("ماتریس بازتاب هاوس‌هولدر H:")
print(H)

# نتیجه ضرب ماتریس H در x
print("\nH * x:")
print(H.dot(x))

ماتریس بازتاب هاوس‌هولدر H:
[[-0.73029674 -0.18257419 -0.54772256 -0.36514837]
 [-0.18257419  0.98073548 -0.05779355 -0.03852904]
 [-0.54772256 -0.05779355  0.82661934 -0.11558711]
 [-0.36514837 -0.03852904 -0.11558711  0.92294193]]

H * x:
[-5.47722558e+00  1.11022302e-16  0.00000000e+00  2.22044605e-16]
